name: scrolling_highlight
description: When you create a listview in Flutter and scroll up and down you will find a highlight color in both.
  To remove ListView highlight color in Flutter you can use it. It is simple and helpful.
version: 1.0.1
repository: https://github.com/rifathossain82/scrolling_highlight.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
